name: generate

on:
  push:
    branches:
      - dev

jobs:
  generate:
    if: github.repository == 'anomalyco/opencode'
    runs-on: ${{ github.repository == 'anomalyco/opencode' && 'blacksmith-4vcpu-ubuntu-2404' || 'ubuntu-latest' }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Bun
        uses: ./.github/actions/setup-bun

      - name: Setup git committer
        if: github.repository == 'anomalyco/opencode'
        id: committer
        uses: ./.github/actions/setup-git-committer
        with:
          opencode-app-id: ${{ vars.OPENCODE_APP_ID }}
          opencode-app-secret: ${{ secrets.OPENCODE_APP_SECRET }}

      - name: Generate
        run: ./script/generate.ts

      - name: Commit and push
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git add -A
          git commit -m "chore: generate" --allow-empty
          git push origin HEAD:${{ github.ref_name }} --no-verify
