name: notify-discord

on:
  release:
    types: [released] # fires when a draft release is published

jobs:
  notify:
    runs-on: ${{ github.repository == 'anomalyco/opencode' && 'blacksmith-4vcpu-ubuntu-2404' || 'ubuntu-latest' }}
    steps:
      - name: Send nicely-formatted embed to Discord
        if: github.repository == 'anomalyco/opencode'
        uses: SethCohen/github-releases-to-discord@24d166886aee4646d448c8a389ff9e1ebcab3682 # v1.20.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
